# Generated by Django 6.0.2 on 2026-02-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPOudit',
            new_name='OTPAudit',
        ),
    ]
